RESTORE DATABASE [SYSWEB_INT] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\Backup\SYSWEB_INT.bak' WITH  FILE = 1,  MOVE N'SYSWEB_INT' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_INT.mdf',  MOVE N'SYSWEB_INT_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_INT_1.ldf',  NOUNLOAD,  STATS = 10
 GO
RESTORE DATABASE [SYSWEB_ADM] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\Backup\SYSWEB_ADM.bak' WITH  FILE = 1,  MOVE N'SYSWEB_ADM' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_ADM.mdf',  MOVE N'SYSWEB_ADM_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_ADM_1.ldf',  NOUNLOAD,  STATS = 10
 GO
RESTORE DATABASE [SYSWEB_ACT] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\Backup\SYSWEB_ACT.bak' WITH  FILE = 1,  MOVE N'SYSWEB_ACT' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_ACT.mdf',  MOVE N'SYSWEB_ACT_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_ACT_1.ldf',  NOUNLOAD,  STATS = 10
 GO
RESTORE DATABASE [SYSWEB_BIT] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\Backup\SYSWEB_BIT.bak' WITH  FILE = 1,  MOVE N'SYSWEB_BIT' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_BIT.mdf',  MOVE N'SYSWEB_BIT_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.SWNOVA_16\MSSQL\DATA\SYSWEB_BIT_1.ldf',  NOUNLOAD,  STATS = 10
 GO
