--CREA LA TEMPORAL

CREATE TABLE [swe].[Z_EMPLEADO](
	[EMP_IntCodigo] [int] NOT NULL,
	[EPL_IntCodigo] [int] NOT NULL,
	[EPL_ChrCedula] [varchar](50) NOT NULL,
	[EPL_FecFechaIngPLN] [datetime] NOT NULL)
	
	
INSERT INTO [swe].[Z_EMPLEADO]	
SELECT 43,'','401950236','2015-08-24 00:00:00.000' UNION ALL
SELECT 43,'','113690109','2014-09-16 00:00:00.000' UNION ALL
SELECT 43,'','107620089','2008-10-21 00:00:00.000' UNION ALL
SELECT 43,'','115220276','2014-07-07 00:00:00.000' UNION ALL
SELECT 43,'','111180035','2012-10-29 00:00:00.000' UNION ALL
SELECT 43,'','110680763','2015-12-01 00:00:00.000' UNION ALL
SELECT 43,'','800840794','2008-01-11 00:00:00.000'	
	
SELECT * FROM [swe].[Z_EMPLEADO]
	
-- ACTUALIZA CODIGO EMPLEADO 

UPDATE SWE.Z_EMPLEADO SET
SWE.Z_EMPLEADO.EPL_IntCodigo  = SWE.SWTRHU_EMPLEADO.EPL_IntCodigo 
FROM SWE.Z_EMPLEADO,SWE.SWTRHU_EMPLEADO
WHERE SWE.Z_EMPLEADO.EMP_IntCodigo  = SWE.SWTRHU_EMPLEADO.EMP_IntCodigo 
AND  SWE.Z_EMPLEADO.EPL_ChrCedula  = SWE.SWTRHU_EMPLEADO.EPL_ChrCedula 

SELECT * FROM [swe].[Z_EMPLEADO] WHERE EPL_IntCodigo = 0

-- VERIFICA LOS EMPLEADOS QUE ESTAN Y NO ESTAN EN LA TEMPORAL 
SELECT * FROM SWE.SWTRHU_EMPLEADO WHERE EMP_IntCodigo = 43 AND EPL_INTCODIGO 
NOT IN (SELECT EPL_INTCODIGO FROM SWE.Z_EMPLEADO)

SELECT * FROM SWE.SWTRHU_EMPLEADO WHERE EMP_IntCodigo = 43 AND EPL_INTCODIGO 
 IN (SELECT EPL_INTCODIGO FROM SWE.Z_EMPLEADO)



SELECT
	
	E.EPL_ChrCedula,
	E.EPL_IntCodigo,
	E.EPL_FecFechaIngPLN AS FECACT, 
	T.EPL_FecFechaIngPLN AS FECNUE
FROM [SYSWEB_ACT].[swe].[SWTRHU_EMPLEADO] E
INNER JOIN swe.Z_EMPLEADO T
ON E.EMP_IntCodigo = T.EMP_IntCodigo
AND E.EPL_ChrCedula = T.EPL_ChrCedula 


--- ACTUALIZA DATOS EN EMPLEADO 

UPDATE SWE.SWTRHU_EMPLEADO SET
SWE.SWTRHU_EMPLEADO.EPL_FecFechaIngPLN = SWE.Z_EMPLEADO.EPL_FecFechaIngPLN 
FROM SWE.SWTRHU_EMPLEADO,SWE.Z_EMPLEADO
WHERE SWE.SWTRHU_EMPLEADO.EMP_IntCodigo  = SWE.Z_EMPLEADO.EMP_IntCodigo 
AND  SWE.SWTRHU_EMPLEADO.EPL_IntCodigo  = SWE.Z_EMPLEADO.EPL_IntCodigo 

SELECT * FROM SWE.SWTRHU_EMPLEADO WHERE EMP_IntCodigo = 43 AND EPL_INTCODIGO 
 IN (SELECT EPL_INTCODIGO FROM SWE.Z_EMPLEADO)
 
-- ACTUALIZA DATO EN EMPLEADO X PLANILLA 

UPDATE SWE.SWTRHU_EMPLEADO_X_PLANILLA SET
SWE.SWTRHU_EMPLEADO_X_PLANILLA.EXP_FecFechaIng = SWE.Z_EMPLEADO.EPL_FecFechaIngPLN 
FROM SWE.SWTRHU_EMPLEADO_X_PLANILLA,SWE.Z_EMPLEADO
WHERE SWE.SWTRHU_EMPLEADO_X_PLANILLA.EMP_IntCodigo  = SWE.Z_EMPLEADO.EMP_IntCodigo 
AND  SWE.SWTRHU_EMPLEADO_X_PLANILLA.EPL_IntCodigo  = SWE.Z_EMPLEADO.EPL_IntCodigo 


SELECT * FROM SWE.SWTRHU_EMPLEADO_X_PLANILLA WHERE EMP_IntCodigo = 43 AND EPL_INTCODIGO 
 IN (SELECT EPL_INTCODIGO FROM SWE.Z_EMPLEADO)

-- ACTUALIZA DATO EN ACCIONES DE PERSONAL 

ALTER TABLE SWE.Z_EMPLEADO 
ADD  ACP_ChrNumero varchar(50) not null default ''

UPDATE SWE.Z_EMPLEADO SET
SWE.Z_EMPLEADO.ACP_ChrNumero = SWE.SWTRHU_ACCION_PERSONAL_ENC.ACP_ChrNumero 
FROM SWE.Z_EMPLEADO, SWE.SWTRHU_ACCION_PERSONAL_ENC
WHERE SWE.Z_EMPLEADO.EMP_IntCodigo =SWE.SWTRHU_ACCION_PERSONAL_ENC.EMP_IntCodigo  
AND  SWE.Z_EMPLEADO.EPL_IntCodigo  = SWE.SWTRHU_ACCION_PERSONAL_ENC.EPL_IntCodigo 
AND SWE.SWTRHU_ACCION_PERSONAL_ENC.ACP_ChrCodigo= 'ACP00001' 

SELECT * FROM SWE.Z_EMPLEADO 

select 
APE.*
from swe.SWTRHU_ACCION_PERSONAL_ENC APE
INNER JOIN (
			SELECT
				T.EMP_INTCODIGO,
				E.EPL_ChrCedula,
				E.EPL_IntCodigo,
				E.EPL_FecFechaIngPLN AS FECACT, 
				T.EPL_FecFechaIngPLN AS FECNUE
			FROM [SYSWEB_ACT].[swe].[SWTRHU_EMPLEADO] E
			INNER JOIN swe.Z_EMPLEADO T
			ON E.EMP_IntCodigo = T.EMP_IntCodigo
			AND E.EPL_ChrCedula = T.EPL_ChrCedula 
			) AS E
ON APE.EMP_IntCodigo = E.EMP_IntCodigo
AND APE.EPL_IntCodigo = E.EPL_IntCodigo 
AND APE.ACP_ChrCodigo = 'ACP00001' 

SELECT  DT.ATR_ChrDato, Z.EPL_FecFechaIngPLN,CONVERT(VARCHAR, Z.EPL_FecFechaIngPLN,101)+' '+CONVERT(VARCHAR, Z.EPL_FecFechaIngPLN,108)
FROM SWE.SWTRHU_ACCION_PERSONAL_DETATR DT
INNER JOIN SWE.Z_EMPLEADO Z 
ON DT.EMP_IntCodigo = Z.EMP_IntCodigo
AND DT.ACP_ChrNumero = Z.ACP_ChrNumero
AND DT.ATR_ChrClave = 'fecFechaIngresoAPlanilla'


UPDATE SWE.SWTRHU_ACCION_PERSONAL_DETATR SET 
SWE.SWTRHU_ACCION_PERSONAL_DETATR.ATR_ChrDato = CONVERT(VARCHAR, SWE.Z_EMPLEADO.EPL_FecFechaIngPLN,101)+' '+CONVERT(VARCHAR, SWE.Z_EMPLEADO.EPL_FecFechaIngPLN,108)
FROM SWE.SWTRHU_ACCION_PERSONAL_DETATR, SWE.Z_EMPLEADO
WHERE SWE.SWTRHU_ACCION_PERSONAL_DETATR.EMP_IntCodigo =SWE.Z_EMPLEADO.EMP_IntCodigo  
AND  SWE.SWTRHU_ACCION_PERSONAL_DETATR.ACP_ChrNumero  = SWE.Z_EMPLEADO.ACP_ChrNumero 
AND SWE.SWTRHU_ACCION_PERSONAL_DETATR.ATR_ChrClave= 'fecFechaIngresoAPlanilla' 

SELECT * FROM SWE.SWTRHU_ACCION_PERSONAL_DETATR
WHERE EMP_IntCodigo = 43 
AND ATR_ChrClave= 'fecFechaIngresoAPlanilla'


-- BORRA TABLA TEMPORAL 

DROP TABLE SWE.Z_EMPLEADO 














