
--------------------------------------------------------------------------------SELECCIONA LAS EMPRESA DISPOSINOBLES
SELECT * FROM SYSWEB_ACT.SWE.SWTEMP_EMPRESA

--------------------------------------------------------------------------------SELECCIONA LOS USUARIOS  DE X EMRPESA
SELECT * FROM SYSWEB_ACT.SWE.SWTEMP_USUARIO WHERE EMP_INTCODIGO = 45

--------------------------------------------------------------------------------SELECCIONA LAS TRANSACICONES GENERADAS POR X USUARIOS
SELECT 
	USU_INTCODIGOING, 
	* 
FROM SYSWEB_ACT.SWE.SWTCOM_TRANSACCION_ENC
WHERE EMP_INTCODIGO = 45
	AND TRA_CHRNUMERO LIKE 'C03%'
	AND USU_INTCODIGOING = 11
ORDER BY TRA_FECFECHAPRC DESC

----------------------------------------------------------------------------------BITACORA DE TRANSACICONES 
DECLARE @TRANSAC VARCHAR(50)
SET @TRANSAC = 'C02-00000391' 

SELECT 
	CONVERT(VARCHAR(MAX), 
	DECRYPTBYPASSPHRASE('KIDFAROCADENJK', BIT_BinDatos)) AS DATOS, * 
FROM (
	SELECT * FROM SYSWEB_BIT.SWE.SWTCOM_BITTRANSACCION_ENC
	WHERE EMP_INTCODIGO = 45 
	AND TRA_CHRNUMERO = @TRANSAC
) AS T


----------------------------------------------------------------------------------BITACORA DE USUARIOS
DECLARE @NOMBRE VARCHAR (50)
SET @NOMBRE = 'JIMMY'

SELECT 
	* 
FROM (

	SELECT 
		CONVERT(VARCHAR(MAX), 
		DECRYPTBYPASSPHRASE('KIDFAROCADENJK', BIT_BINDATOS)) AS DATO,
		* 
	FROM 
		SYSWEB_BIT.SWE.SWTEMP_BITUSUARIO
	WHERE 
		EMP_INTCODIGO = 45 
		--AND BIT_FECFECHA BETWEEN '2015-10-09' AND '2015-10-09 20:11:42.110'
 ) AS T
 WHERE 
	 T.DATO LIKE '%JIMMY%'
	 OR T.DATO LIKE '%OVER%'


