--[6]-- MUESTRA LA CONFIGURACIÓN GENERAL DE LOS CGE CONFIGURADOS
--		PARA ESTABLECER SI EL MODULO DE DESPACHO DEBE ESTAR ACTIVO O NO
SELECT 
	 CNF.CGE_IntCodigo
	,CNF.ADM_ChrConfiguracion
	,CNF.ADM_ChrAcceso
	,CNF.ADM_BinDato
	,CONVERT(VARCHAR,DECRYPTBYPASSPHRASE('KIDFAROCADENJK', CNF.ADM_BinDato)) AS ADM_BinDatoDES
FROM 
	SYSWEB_ADM.swe.SWTADM_CONFIGURACION CNF
WHERE
	ADM_ChrConfiguracion = 'CGEModComercial_DSP'
	
/*	
--// ACTUALIZA MODULO DE DESPACHO COMO NO CONFIGURADO	
UPDATE SYSWEB_ADM.swe.SWTADM_CONFIGURACION
SET ADM_BinDato = ENCRYPTBYPASSPHRASE('KIDFAROCADENJK','0')
WHERE
	CGE_IntCodigo = 1
	AND ADM_ChrConfiguracion = 'CGEModComercial_DSP'
*/
