UPDATE SYSWEB_ADM.swe.SWTADM_CONFIGURACION
SET ADM_BinDato = ENCRYPTBYPASSPHRASE('KIDFAROCADENJK','1')
WHERE
	CGE_IntCodigo = 1 --- OJO CAMBIAR CODIGO CGE  
	AND ADM_ChrConfiguracion = 'CGEModComercial_DSP'