SELECT [CGE_IntCodigo]
      ,[ADM_ChrConfiguracion]
      ,[ADM_ChrAcceso]
      ,CONVERT(VARCHAR(500), DECRYPTBYPASSPHRASE('KIDFAROCADENJK',[ADM_BinDato]))
  FROM [SYSWEB_ADM].[swe].[SWTADM_CONFIGURACION]
GO

UPDATE [SYSWEB_ADM].[swe].[SWTADM_CONFIGURACION]
SET [ADM_BinDato] = ENCRYPTBYPASSPHRASE('KIDFAROCADENJK','1')

UPDATE [SYSWEB_ADM].[swe].[SWTADM_CONFIGURACION]
SET [ADM_BinDato] = ENCRYPTBYPASSPHRASE('KIDFAROCADENJK','50')
WHERE ADM_ChrConfiguracion = 'CGEConcUsuarios'


UPDATE [SYSWEB_ADM].[swe].[SWTADM_CONFIGURACION]
SET [ADM_BinDato] = ENCRYPTBYPASSPHRASE('KIDFAROCADENJK','5')
WHERE ADM_ChrConfiguracion = 'CGEConcEmpresas'

INSERT INTO [SYSWEB_ADM].[swe].[SWTADM_CONFIGURACION]
SELECT 4 AS [CGE_IntCodigo]
      ,[ADM_ChrConfiguracion]
      ,[ADM_ChrAcceso]
      ,ENCRYPTBYPASSPHRASE('KIDFAROCADENJK',CONVERT(VARCHAR(500), DECRYPTBYPASSPHRASE('KIDFAROCADENJK',[ADM_BinDato])))
  FROM [SYSWEB_ADM].[swe].[SWTADM_CONFIGURACION]
  where [CGE_IntCodigo] = 1
GO




