-- BORRA CAJA CHICA Y DETALLE 

DELETE from SWE.SWTFNC_CAJACHICA_DETGAS where EMP_IntCodigo = 44

DELETE FROM SWE.SWTFNC_CAJACHICA_DETPROC  where EMP_IntCodigo = 44

DELETE FROM SWE.SWTFNC_CAJACHICA_SLQDET where EMP_IntCodigo = 44
DELETE FROM SWE.SWTFNC_CAJACHICA_SLQENC where EMP_IntCodigo = 44


DELETE from SWE.SWTFNC_CAJACHICA where EMP_IntCodigo = 44

-- BORRA CONCILIACIONES 

DELETE from SWE.SWTFNC_CONCIL_DET_ANCONC where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_CONCIL_DET_ESTADOS where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_CONCIL_DET_SNCONC where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_CONCIL_DET_SSCONC where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_CONCIL_ENC where EMP_IntCodigo = 44

-- BORRA LOTES MEDIO PAGO 

DELETE from SWE.SWTFNC_LOTE_LIQDET_DED where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_LIQDET_EST where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_LIQDET_TRA where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_LIQENC where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_MPGDET_DED where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_MPGDET_EST where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_MPGDET_TRA where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_LOTE_MPGENC where EMP_IntCodigo = 44


-- BORRA PRESTAMOS 

DELETE from SWE.SWTFNC_PRESTAMO_DETMOV where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_PRESTAMO_DETTAS where EMP_IntCodigo = 44
DELETE from SWE.SWTFNC_PRESTAMO_ENC where EMP_IntCodigo = 44

-- VERIFICAR CAJAS  

DELETE from SWE.SWTCOM_TRANSAC_CAJA_PROCESO_DET where EMP_IntCodigo = 44
DELETE from SWE.SWTCOM_TRANSAC_CAJA_PROCESO where EMP_IntCodigo = 44
 
-- actualiza fecha caja a inicio periodo  
select * from SWE.SWTCOM_TRANSAC_CAJA where EMP_IntCodigo = 44

UPDATE SWE.SWTCOM_TRANSAC_CAJA SET 
CAJ_BndAbierta = 0,
USU_FecFechaIng ='2015-10-01',
USU_FecFechaMod = '2015-10-01',
USU_IntCodigoCaj = 0 
WHERE EMP_IntCodigo = 44 



-- VERIFICA DESPACHOS 

DELETE FROM SWE.SWTDSP_DESPACHO_DETINV WHERE EMP_IntCodigo = 44
DELETE FROM SWE.SWTDSP_DESPACHO_DETDOC WHERE EMP_IntCodigo = 44
DELETE FROM SWE.SWTDSP_DESPACHO_DETEST WHERE EMP_IntCodigo = 44
DELETE FROM SWE.SWTDSP_DESPACHO_ENC WHERE EMP_IntCodigo = 44




